version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: ./scripts/test.Dockerfile
    container_name: field-seating-test-server
    working_dir: /var/app
    volumes:
      - ./src:/var/app/src
      - ./prisma:/var/app/prisma
      - ./scripts:/var/app/scripts
    networks:
      - application
    depends_on:
      - database
      - redis
    environment:
      APP_ENV: test
      DATABASE_URL: mysql://root:root@field-seating-test-db:3306/field_seating_test
      JWT_SECRET: jwt_secret
      SIB_KEY: "sibKey"
      EMAIL: YOUR_EMAIL
      REDIS_URL: redis://field-seating-test-redis:6379
      SENDGRID_SANDBOX_MODE: true

  database:
    image: mysql:8
    container_name: field-seating-test-db
    platform: linux/amd64
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - 3306
    networks:
      - application

  redis:
    image: redis:6.2
    container_name: field-seating-test-redis
    platform: linux/amd64
    restart: always
    expose:
      - 3306
    networks:
      - application
networks:
  application:
