version: "3.9"

services:
  server:
    image: node:16
    container_name: field-seating-test-server
    command: sh -c "npm run db:deploy && git init && npm run test:watch"
    working_dir: /var/app
    volumes:
      - ../:/var/app
      - ../.env.test:/var/app/.env
    networks:
      - application
    depends_on:
      - database

  database:
    image: mysql:8
    container_name: field-seating-test-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - 3306
    networks:
      - application
networks:
  application:
